<<<<<<< HEAD
version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-30-0

  eslint:
    enabled: true
    channel: "eslint-7"
    exclude_patterns:
      - "!public/js/"
  scss-lint:
    enabled: true

  duplication:
    enabled: true
    exclude_patterns:
      - "spec/"

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.module"

exclude_paths:
- config/
- db/
- vendor/
- public/bootstrap-3.3.7/
- public/external/
- test/
- tmp/
- apidoc/v1/javascripts/
- docs/source/javascripts/

checks:
  method-lines:
      config:
        threshold: 100 # prevent lint errors in js
=======
version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-30-0

  eslint:
    enabled: true
    channel: "eslint-7"
    exclude_patterns:
      - "!public/js/"
  scss-lint:
    enabled: true

  duplication:
    enabled: true
    exclude_patterns:
      - "spec/"

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.module"

exclude_paths:
- config/
- db/
- vendor/
- public/bootstrap-3.3.7/
- public/external/
- test/
- tmp/
- apidoc/v1/javascripts/
- docs/source/javascripts/

checks:
  method-lines:
      config:
        threshold: 100 # prevent lint errors in js
>>>>>>> 1a9b6e3e7e7f36210145d3bd4f13865f9fbd64d7
